version: '3'
services:
  jaeger-query:
    image: jaegertracing/jaeger-query:1.42
    container_name: jaeger-query
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    ports:
      - "16686:16686"
    networks:
      - jaeger
      - elastic
  jaeger-collector:
    image: jaegertracing/jaeger-collector:1.42
    container_name: jaeger-collector
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_TCHANNEL_PORT=14267
      - COLLECTOR_GRPC_PORT=14250
      - AGENT_HOST_PORT=:6831
      - COLLECTOR_HTTP_PORT=14268
    ports:
      - "14250:14250"
      - "14267:14267"
      - "9411:9411"
      - "6831:6831/udp"
      - "14268:14268"
    networks:
      - jaeger
      - elastic
networks:
  jaeger:
    name: jaeger
    driver: bridge
  elastic:
    external: true
      